### ISSUE TITLE
Settings ⭢ General ⭢ VPN ⭢ DNS" doesn't work

### ISSUE THREAD

**Issue by korgoth** [FifiTheBulldog/ios-settings-urls#28] opened 2022-02-19 01:24 UTC
Title: "Settings ⭢ General ⭢ VPN ⭢ DNS" doesn't work
URL: prefs:root=General&path=VPN/DNS
Device: iPhone
OS version: 15.3.1
Language: en

**Comment by FifiTheBulldog** [comment] 2022-02-19 02:48
Duplicate of #16

**Closed by FifiTheBulldog** 2022-02-19 02:48 UTC
